tag_prefix = "v"
from_latest_tag = false
ignore_merge_commits = true
generate_mono_repository_global_tag = true
branch_whitelist = ["main"]
pre_bump_hooks = [
    "poetry version {{version}}",
]
post_bump_hooks = [
    "git push",
    "git push origin v{{version}}",
]

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]

[packages]
